version: '4'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./datasets:/datasets
      - ./postgres-data:/var/lib/postgresql/data
      - ./schema/create_schemas.sql:/docker-entrypoint-initdb.d/create_schemas.sql
      - ./schema/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
    env_file:
      - path: .env


  airflow_pipeline:
    image: airflow_bikestore
    
    user: root
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:1234@postgres:5432/bikestore


    volumes:
      - ./airflow:/opt/airflow
      - ./dbt_bikestore:/opt/dbt
      - ./evidence:/opt/evidence

    env_file:
      - path: .env

    ports:
      - "8080:8080"

    command: ["airflow", "standalone"]

